project:
  type: website
  output-dir: docs

website:
  title: "Bagas' Data Study and Explore"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sagabmonash
format:
  html:
    theme: sandstone
    css: styles.css
